### PR TITLE
fix JSON mapper to use ProtoDescriptorBin value only

### PR DESCRIPTION
**Pull request by sishbi**
- fix JSON mapper to use ProtoDescriptorBin value only, map to proto_descriptor
- correct name of Services argument to 'services'

### CODE REVIEW

**Comment by sishbi** [comment]
@mirkolenz Hello, I have been trying to use `grpc-proxy` but it doesn't work when you supply a binary proto descriptor.
So I modified the tool to use that option exclusively and now it works for me.
Please consider this PR

**Comment by mirkolenz** [comment]
Hi, thanks for spotting this bug and making a PR!

Since I mostly use the proto descriptor with a file (and not as binary content), this would be a breaking change for me. Instead, I checked the code and hope to have found the root cause without needing to remove the possibility to provide the proto descriptor as a file. Now, grpc-proxy checks if any of the arguments has been provided:

```txt
#<- if and .Rest.Services (or .Rest.ProtoDescriptor .Rest.ProtoDescriptorBin) >#
```

Regarding the change of `services`: Since it is a string array, multiple services are passed in the CLI by using multiple `--rest-service`` flags. The same logic applies to all other arrays that are part of the CLI. So I left that as-is.

I just pushed my changes, they are available in [v3.0.2](https://github.com/mirkolenz/grpc-proxy/releases/tag/v3.0.2). I also updated the dependencies (kong and go) while I was at it.

Please let me know if my changes fix your problem 😄

**Comment by sishbi** [comment]
And I tried this myself:
`#<- if and .Rest.Services (or .Rest.ProtoDescriptor .Rest.ProtoDescriptorBin) >#`
But it still included BOTH `.Rest.ProtoDescriptor` and `.Rest.ProtoDescriptorBin` It should only include ONE of those.

**Comment by mirkolenz** [comment]
Thanks for the extremely detailed description, that helped me a lot 👍 

Regarding the `--rest-service` flag: I confused the behavior of typer/click CLIs (used in Python apps) with the behavior of kong: With typer, a list of strings is passed by repeating the flag multiple times, whereas kong uses commas to separate the values. I now updated the flag to `--rest-services` to match the semantics of the kong-way 😄 

Regarding `proto_descriptor`: According to the [envoy API description](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/grpc_json_transcoder/v3/transcoder.proto), `proto_descriptor` should be used to pass file names and `proto_descriptor_bin` to pass binary representations directly. This also reflects my usage of grpc-proxy: I use the `proto_descriptor` entry together with a `.binp` file. If my understanding is correct, it would also explain why envoy complains about the argument value: It expects a base64 representation but receives a plain string instead. Could you give that a try and let me know if it works for you as well?

I just pushed an updated version (v3.0.3) containing some more optimizations and also the renamed `--rest-services` parameter.

PS: Instead of building a custom Dockerfile you could also try the pre-built one, it even contains the envoy binary and should work out-of-the-box (hopefully I did not break it with my recent refactorings, please ping me again if the Docker image doesn't work as expected): https://github.com/mirkolenz/grpc-proxy/pkgs/container/grpc-proxy

**Comment by sishbi** [comment]
Thanks for the update again!
I will give your updated version a try. It's strange that my PR version worked for me when I triggered one of the APIs in my proto file.
But I will try again specifying the file as you suggest.

I would like to use your docker image but couldn't work out how to add the proto descriptor file and using your image as a base with a FROM, it couldn't find the image properly. I can try that again to see if I can find more info for you.

As we deploy into kubernetes and will build this into a pod maybe I can use a config map for the descriptor which I could mount as a file. Let me give that a go instead of building a custom image extending from yours.

**Comment by sishbi** [comment]
I still get the same issue.
Even if I use your docker image I get the issue related to multiple definitions as above.
when I tried to use your image I could not specify the ports using the CMD line as it passes them as strings instead of integers

**Comment by mirkolenz** [comment]
Sorry about the trouble you're having!

I tried running the Docker image today and could replicate the error envoy throws if both `proto_descriptor` and `proto_descriptor_bin` were set. That was not the case the last time I used the image, could it be that envoy got stricter about this in one of its last updates?

Anyway, I added a string replacement strategy that removes the empty descriptor flag so that only one of the settings is stored in the generated `envoy.yaml`.

I could however not replicate the issues with passing the port numbers. With the following call, envoy starts and says `starting workers` once it's ready to receive requests.

```shell
docker run --rm -it -v $(pwd):/data ghcr.io/mirkolenz/grpc-proxy:3.0.4 --proxy-port 50052 --backend-port 50051 --rest-proto-descriptor /data/descriptor.binpb --rest-services "service.xxx.Name"
```

What's missing in the command is the port mapping (so that the docker container can in fact reach the grpc backend).

**Comment by sishbi** [comment]
Here is the Dockerfile I was trying to use:
```
FROM ghcr.io/mirkolenz/grpc-proxy:3.0.3

ADD build/distributions/kp-grpc-rest-gateway.tar /etc

ARG BACKEND_HOST=kp-core-grpc
ARG BACKEND_PORT=80
ARG PROXY_PORT=8080

ENV PROXY_PORT=$PROXY_PORT
ENV BACKEND_HOST=$BACKEND_HOST
ENV BACKEND_PORT=$BACKEND_PORT

CMD ["--proxy-port=$PROXY_PORT", "--proxy-host", "0.0.0.0", "--backend-port=$BACKEND_PORT", "--backend-host", "$BACKEND_HOST", "--backend-timeout", "180", "--no-rest-auto-mapping", "--rest-reject-unknown-method", "--rest-proto-descriptor", "/etc/image.binpb", "--rest-services", "com.kodypay.grpc.pay.v1.KodyPayTerminalService,com.kodypay.grpc.ecom.v1.KodyEcomPaymentsService" ]
```

However, I think trying to use `$BACKEND_PORT` within the CMD array was invalid.
Anyway, thank you for your help!
I have decided to go back to simply using envoy directly, providing a `envoy.yaml` file which uses the transcoder.
So I will not be using your tool going forward, but I really appreciate the support you have provided.
I will now close this PR as I don't think it should be merged now you have fixed the issues with the invalid config.

**Comment by sishbi** [comment]
However, for good measure I did try your change and it seems to work!
Here is what I used for the CMD line:
```
CMD ["--proxy-port=8080", "--proxy-host=0.0.0.0", "--backend-port=80", "--backend-host=kp-core-grpc", "--backend-timeout=180", "--no-rest-auto-mapping", "--rest-reject-unknown-method", "--rest-proto-descriptor=/etc/image.binpb", "--rest-services=com.kodypay.grpc.pay.v1.KodyPayTerminalService,com.kodypay.grpc.ecom.v1.KodyEcomPaymentsService" ]
```

And this is what I get (basically it is working):
```
all dependencies initialized. starting workers
```

**Comment by sishbi** [comment]
I think I still need to use an entry point script to make this work in my own Dockerfile (using envoy) I have to modify the config at runtime, basically doing what you are!

I did try to use your grpc-proxy binary directly in an ENTRYPOINT but the path to binary is not found...
I think it is within a random directory, for example:
```
ENTRYPOINT [ "/nix/store/slnhm8mcfhqsz8whay324f9gl3s8g2rd-grpc-proxy/bin/grpc-proxy", "--help"]
```
Basically the directory `slnhm8mcfhqsz8whay324f9gl3s8g2rd-grpc-proxy` changes with each build...
If the `/bin/grpc-proxy` path was stable then it would make it easier to extend the image as I have done above.

**Comment by mirkolenz** [comment]
Thanks for the update 😄 

> Basically the directory slnhm8mcfhqsz8whay324f9gl3s8g2rd-grpc-proxy changes with each build. If the /bin/grpc-proxy path was stable then it would make it easier to extend the image as I have done above.

That is because the image is built directly with nix and I use the plain store path for the entrypoint. However, I think your use case of overriding the image is totally valid and just pushed some changes that make grpc-proxy and envoy available as symlinks in `/bin` as well, so the binaries in this path can be used for further image customization: https://github.com/mirkolenz/grpc-proxy/releases/tag/v3.0.5

Let me know if that helps or if further changes are necessary.

**Comment by mirkolenz** [comment]
Oh and by the way, the Docker image already uses the following default options via the defined entrypoint:

```nix
{
  proxy-host = "0.0.0.0";
  admin-host = "0.0.0.0";
  backend-host = "host.docker.internal";
};
```

In theory, you only need to pass any additional flags via a custom `CMD` and could leave the entrypoint as-is.

**Comment by sishbi** [comment]
I did try leaving those options off the CMD but the image didn't start, saying they weren't configured. But maybe that was the missing port. I tried a few combinations today.
If you can fix the issue if the port is specified as a string and auto-convert to an int that would help too!

I will try using your new version now that I can use the symlinked binary in an entry point script.

Thanks again for the speedy support!

**Comment by mirkolenz** [comment]
AFAIK the ports are always passed as a string and converted to integers automatically via kong. Maybe the issue was that the port was somehow empty? In case you stumble upon this issue again feel free to post the error you are getting from grpc-proxy, I'll do further investigations then 😄

**Pull request closed without merging**
